name: Daily News Mail

on:
  workflow_dispatch:  # 수동 실행용
  schedule:
    - cron: '0 14 * * 3'  # 매주 수요일 동부시간 오전 10시

jobs:
  send_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'   # 🔥 핵심 (속도 개선)

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: wkhtmltopdf 설치
        run: sudo apt-get install -y wkhtmltopdf  

#      - name: Print envs (debug)
#        run: |
#          echo "EMAIL: $EMAIL"
#          echo "APP_PASSWORD: $APP_PASSWORD"
#          echo "NEWS_API_KEY: $NEWS_API_KEY"
#          echo "RECIPIENTS: $RECIPIENTS"
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}

      - name: Send Daily News
        run: python main.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}