name: Daily News Mail

on:
  workflow_dispatch: # 수동 테스트용
  schedule:
    - cron: '0 14 * * 3'  # 매주수요일 동부시간 오전 10시

jobs:
  send_news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Show current dir
        run: pwd
      - name: Show files
        run: ls -R    
      - name: Install dependencies
        run:  pip install -r requirements.txt
      - name: Send Daily News
        run: python main.py
    env:
      EMAIL: ${{ secrets.EMAIL }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      RECIPIENTS: ${{ secrets.RECIPIENTS }}